name: Headless E2E

on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - "cmd/**"
      - "pkg/**"
      - "integration/**"
      - "Dockerfile.e2e"
      - "integration/docker-compose.e2e.yml"
      - ".github/workflows/e2e.yml"

jobs:
  linux-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build images
        run: docker compose -f integration/docker-compose.e2e.yml build

      - name: Run headless e2e
        run: docker compose -f integration/docker-compose.e2e.yml up tester --abort-on-container-exit

      - name: Show logs on failure
        if: failure()
        run: docker compose -f integration/docker-compose.e2e.yml logs